### PR TITLE
Add Fetch API types as accepted mock parameters

### LINKED ISSUE #233: Typescript: Type 'string' is not assignable to type 'Body | undefined'
I found that `Body` interface supports only `[key: string]: any;`. But in many projects, the body may include stringified JSON, like this:
```
const { req, res } = createMocks({
      method: 'POST',
      body: JSON.stringify({ config: 'some config' }),
    });
```
Because of that, the `eslint` throws the error below:
error

Probably, we can add a type like `export type BodyString = string;` and apply it to the `RequestOptions` interface like this:
```
    export interface RequestOptions {
        method?: RequestMethod;
        url?: string;
        originalUrl?: string;
        baseUrl?: string;
        path?: string;
        params?: Params;
        session?: Session;
        cookies?: Cookies;
        signedCookies?: Cookies;
        headers?: Headers;
        body?: Body | BodyString;         // or BodyString
        query?: Query;
        files?: Files;

        // Support custom properties appended on Request objects.
        [key: string]: any;
    }
```

It will solve the issue for eslint users. Probably there is a more elegant solution but the idea remains the same.
Also, any workarounds are welcome!

### PR DESCRIPTION
**Pull request by mhaligowski**
Adds Fetch API's `Request` and `Response` objects to accepted generic types, allowing for using objects that extend this, e.g. [NextJS](https://nextjs.org/docs/app/api-reference/functions/next-request) App Router.

fixes #233

### CODE REVIEW

**Comment by mhaligowski** [comment]
@eugef what's up with this? I guess I need to update the branch, right?

**Comment by eugef** [comment]
Hi @mhaligowski 

If you can run `npm run format` and commit the changes then I would be able to merge this PR

**Comment by mhaligowski** [comment]
@eugef sorry, on it!

**Comment by eugef** [comment]
@mhaligowski no problem, thanks for updating PR

**Pull request merged**
